language: rust

rust:
    - nightly
    - beta
    - stable

os:
    - osx
    - linux

script:
    - cargo build --verbose
    - cargo test --verbose
    - cargo test --features="serde_serialization" --verbose
    - cargo doc --verbose
